//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 🔴 Fail to set text in clipboard 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_failed {
            get {
                return ResourceManager.GetString("everything_clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🟢 Successfully copied to clipboard! 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_success {
            get {
                return ResourceManager.GetString("everything_clipboard_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string everything_copied {
            get {
                return ResourceManager.GetString("everything_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path 的本地化字符串。
        /// </summary>
        internal static string everything_copy_path {
            get {
                return ResourceManager.GetString("everything_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete file 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file {
            get {
                return ResourceManager.GetString("everything_delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete &quot;{0}&quot; file? 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file_tips {
            get {
                return ResourceManager.GetString("everything_delete_file_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete folder 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder {
            get {
                return ResourceManager.GetString("everything_delete_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the &quot;{0}&quot; folder (including its files and subfolders) 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder_tips {
            get {
                return ResourceManager.GetString("everything_delete_folder_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string everything_delete_tips_caption {
            get {
                return ResourceManager.GetString("everything_delete_tips_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string everything_file_does_not_exit {
            get {
                return ResourceManager.GetString("everything_file_does_not_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a file, not a folder 的本地化字符串。
        /// </summary>
        internal static string everything_file_is_file_not_folder {
            get {
                return ResourceManager.GetString("everything_file_is_file_not_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string everything_folder_browse {
            get {
                return ResourceManager.GetString("everything_folder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This folder is empty 的本地化字符串。
        /// </summary>
        internal static string everything_folder_is_empty {
            get {
                return ResourceManager.GetString("everything_folder_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to open folder at 的本地化字符串。
        /// </summary>
        internal static string everything_folder_open_failed {
            get {
                return ResourceManager.GetString("everything_folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GoBack 的本地化字符串。
        /// </summary>
        internal static string everything_go_back {
            get {
                return ResourceManager.GetString("everything_go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # CmdPal Everything Help Document
        ///&gt; CmdPal Everything is a command panel extension for Windows that allows you to quickly access files and folders in the Everything database through the command panel.
        ///
        ///## Everything Features (Please refer to the official website for details)
        ///- **Quick Access**: Through the command panel, you can quickly find and open files and folders without using the file explorer.
        ///- **Search**: Supports searching for file and folder names, paths, extensions, etc.
        ///- **Sort**: Suppor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string everything_help_content {
            get {
                return ResourceManager.GetString("everything_help_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help document 的本地化字符串。
        /// </summary>
        internal static string everything_help_title {
            get {
                return ResourceManager.GetString("everything_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything is not running 的本地化字符串。
        /// </summary>
        internal static string everything_is_not_running {
            get {
                return ResourceManager.GetString("everything_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable macro query 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled {
            get {
                return ResourceManager.GetString("everything_macro_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available doc:,audio:,zip:,pic:,video:,web: and exe: and so filters macro search files 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled_description {
            get {
                return ResourceManager.GetString("everything_macro_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string everything_name {
            get {
                return ResourceManager.GetString("everything_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string everything_open {
            get {
                return ResourceManager.GetString("everything_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open containing folder 的本地化字符串。
        /// </summary>
        internal static string everything_open_containing_folder {
            get {
                return ResourceManager.GetString("everything_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder 的本地化字符串。
        /// </summary>
        internal static string everything_open_folder {
            get {
                return ResourceManager.GetString("everything_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open path in console 的本地化字符串。
        /// </summary>
        internal static string everything_open_in_console {
            get {
                return ResourceManager.GetString("everything_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string everything_path {
            get {
                return ResourceManager.GetString("everything_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for files or folders using Everything 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_description {
            get {
                return ResourceManager.GetString("everything_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything Search 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_name {
            get {
                return ResourceManager.GetString("everything_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything query error 的本地化字符串。
        /// </summary>
        internal static string everything_query_error {
            get {
                return ResourceManager.GetString("everything_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_administrator {
            get {
                return ResourceManager.GetString("everything_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as different user 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_user {
            get {
                return ResourceManager.GetString("everything_run_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        internal static string everything_subtitle_header {
            get {
                return ResourceManager.GetString("everything_subtitle_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview {
            get {
                return ResourceManager.GetString("everything_text_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current file does not support preview！ 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview_not_supported {
            get {
                return ResourceManager.GetString("everything_text_preview_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to use Everything search 的本地化字符串。
        /// </summary>
        internal static string everything_welcome {
            get {
                return ResourceManager.GetString("everything_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type the &apos;Enter&apos; key for help information 的本地化字符串。
        /// </summary>
        internal static string everything_welcome_subtitle {
            get {
                return ResourceManager.GetString("everything_welcome_subtitle", resourceCulture);
            }
        }
    }
}
