//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___复制 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___复制() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingExtension.Properties.Resources - 复制", typeof(Resources___复制).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 🔴 设置到剪贴板失败！ 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_failed {
            get {
                return ResourceManager.GetString("everything_clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🟢 已成功设置到剪贴板！ 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_success {
            get {
                return ResourceManager.GetString("everything_clipboard_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string everything_copied {
            get {
                return ResourceManager.GetString("everything_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制文件或文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_copy_file {
            get {
                return ResourceManager.GetString("everything_copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制路径 的本地化字符串。
        /// </summary>
        internal static string everything_copy_path {
            get {
                return ResourceManager.GetString("everything_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file {
            get {
                return ResourceManager.GetString("everything_delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除 “{0}” 文件吗 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file_tips {
            get {
                return ResourceManager.GetString("everything_delete_file_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder {
            get {
                return ResourceManager.GetString("everything_delete_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除 “{0}” 文件夹（包含其中的文件和子文件夹）吗？ 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder_tips {
            get {
                return ResourceManager.GetString("everything_delete_folder_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string everything_delete_tips_caption {
            get {
                return ResourceManager.GetString("everything_delete_tips_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索匹配多个项 的本地化字符串。
        /// </summary>
        internal static string everything_fallback_multipleResults_subtitle {
            get {
                return ResourceManager.GetString("everything_fallback_multipleResults_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件不存在 的本地化字符串。
        /// </summary>
        internal static string everything_file_does_not_exit {
            get {
                return ResourceManager.GetString("everything_file_does_not_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个文件，不是文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_file_is_file_not_folder {
            get {
                return ResourceManager.GetString("everything_file_is_file_not_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找文件或文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_find_fallback_display_title {
            get {
                return ResourceManager.GetString("everything_find_fallback_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string everything_folder_browse {
            get {
                return ResourceManager.GetString("everything_folder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件夹为空 的本地化字符串。
        /// </summary>
        internal static string everything_folder_is_empty {
            get {
                return ResourceManager.GetString("everything_folder_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_folder_open_failed {
            get {
                return ResourceManager.GetString("everything_folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string everything_go_back {
            get {
                return ResourceManager.GetString("everything_go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # CmdPal Everything 帮助文档
        ///&gt; CmdPal Everything 是一个用于 Windows 的命令面板扩展，它允许您通过命令面板快速访问 Everything 数据库中的文件和文件夹。
        ///
        ///## Everything 功能（具体请参考[官网](https://www.voidtools.com/zh-cn/)文案）
        ///- **快速访问**：通过命令面板，您可以快速找到并打开文件和文件夹，无需使用文件资源管理器。
        ///- **搜索**：支持搜索文件和文件夹的名称、路径、扩展名等。
        ///- **排序**：支持按名称、大小、修改日期等对搜索结果进行排序。
        ///- **过滤**：支持过滤文件和文件夹的扩展名、类型等。
        ///- **预览**：支持预览文件的内容，包括文本文件、图片、视频等。
        ///- **运行**：支持以管理员身份运行文件。
        ///- **复制路径**：支持复制文件和文件夹的路径。
        ///- **更多功能**：支持更多高级功能，如创建快捷方式、重命名文件和文件夹等。
        ///
        ///## CmdPal Everything 使用方法
        ///1. 输入 `Everything`（或选择 `Everything [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string everything_help_content {
            get {
                return ResourceManager.GetString("everything_help_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助文档 的本地化字符串。
        /// </summary>
        internal static string everything_help_title {
            get {
                return ResourceManager.GetString("everything_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]是否忽略标点符号 的本地化字符串。
        /// </summary>
        internal static string everything_ignorePunctuation_enabled {
            get {
                return ResourceManager.GetString("everything_ignorePunctuation_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索时自动忽略中英文各类标点符号 的本地化字符串。
        /// </summary>
        internal static string everything_ignorePunctuation_enabled_description {
            get {
                return ResourceManager.GetString("everything_ignorePunctuation_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]是否忽略空白字符 的本地化字符串。
        /// </summary>
        internal static string everything_ignoreWhitespace_enabled {
            get {
                return ResourceManager.GetString("everything_ignoreWhitespace_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略空格、制表符等全部空白字符 的本地化字符串。
        /// </summary>
        internal static string everything_ignoreWhitespace_enabled_description {
            get {
                return ResourceManager.GetString("everything_ignoreWhitespace_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 未运行 的本地化字符串。
        /// </summary>
        internal static string everything_is_not_running {
            get {
                return ResourceManager.GetString("everything_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类标签 的本地化字符串。
        /// </summary>
        internal static string everything_item_tags_name {
            get {
                return ResourceManager.GetString("everything_item_tags_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用宏查询 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled {
            get {
                return ResourceManager.GetString("everything_macro_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用doc:、audio:、zip:、pic:、video:、web: 和 exe:等过滤器搜索文件 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled_description {
            get {
                return ResourceManager.GetString("everything_macro_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否区分大小写 的本地化字符串。
        /// </summary>
        internal static string everything_matchCase_enabled {
            get {
                return ResourceManager.GetString("everything_matchCase_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后搜索区分英文字母大小写，A与a视为不同字符 的本地化字符串。
        /// </summary>
        internal static string everything_matchCase_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchCase_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]是否区分变音符号 的本地化字符串。
        /// </summary>
        internal static string everything_matchDiacritics_enabled {
            get {
                return ResourceManager.GetString("everything_matchDiacritics_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分带重音变音字符，é、à等字符不会和普通字母匹配 的本地化字符串。
        /// </summary>
        internal static string everything_matchDiacritics_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchDiacritics_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否匹配路径(包括路径部分) 的本地化字符串。
        /// </summary>
        internal static string everything_matchPath_enabled {
            get {
                return ResourceManager.GetString("everything_matchPath_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索包含完整目录路径，关键词可匹配文件夹路径内容 的本地化字符串。
        /// </summary>
        internal static string everything_matchPath_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchPath_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]是否前缀匹配 的本地化字符串。
        /// </summary>
        internal static string everything_matchPrefix_enabled {
            get {
                return ResourceManager.GetString("everything_matchPrefix_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅匹配文件名或路径开头的关键词内容 的本地化字符串。
        /// </summary>
        internal static string everything_matchPrefix_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchPrefix_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]是否后缀匹配 的本地化字符串。
        /// </summary>
        internal static string everything_matchSuffix_enabled {
            get {
                return ResourceManager.GetString("everything_matchSuffix_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅匹配文件名或路径末尾的关键词内容 的本地化字符串。
        /// </summary>
        internal static string everything_matchSuffix_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchSuffix_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否全字匹配 的本地化字符串。
        /// </summary>
        internal static string everything_matchWholeWords_enabled {
            get {
                return ResourceManager.GetString("everything_matchWholeWords_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅完整匹配整个单词，不匹配单词内部局部字符 的本地化字符串。
        /// </summary>
        internal static string everything_matchWholeWords_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchWholeWords_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索结果限制 的本地化字符串。
        /// </summary>
        internal static string everything_max_search_result_limit {
            get {
                return ResourceManager.GetString("everything_max_search_result_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索结果最大的返回数量（数量过多会导致 CmdPal 崩溃） 的本地化字符串。
        /// </summary>
        internal static string everything_max_search_result_limit_description {
            get {
                return ResourceManager.GetString("everything_max_search_result_limit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string everything_name {
            get {
                return ResourceManager.GetString("everything_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string everything_open {
            get {
                return ResourceManager.GetString("everything_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所在文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_open_containing_folder {
            get {
                return ResourceManager.GetString("everything_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_open_folder {
            get {
                return ResourceManager.GetString("everything_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在控制台中打开路径 的本地化字符串。
        /// </summary>
        internal static string everything_open_in_console {
            get {
                return ResourceManager.GetString("everything_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string everything_path {
            get {
                return ResourceManager.GetString("everything_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 Everything 搜索文件或文件夹 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_description {
            get {
                return ResourceManager.GetString("everything_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 搜索 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_name {
            get {
                return ResourceManager.GetString("everything_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_settings {
            get {
                return ResourceManager.GetString("everything_plugin_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 查询错误 的本地化字符串。
        /// </summary>
        internal static string everything_query_error {
            get {
                return ResourceManager.GetString("everything_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未检测到 Everything 服务，请手动启动 Everything 后再次重试！ 的本地化字符串。
        /// </summary>
        internal static string everything_reconnect_fail_message {
            get {
                return ResourceManager.GetString("everything_reconnect_fail_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测并连接成功！ 的本地化字符串。
        /// </summary>
        internal static string everything_reconnect_success_message {
            get {
                return ResourceManager.GetString("everything_reconnect_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以管理员身份运行 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_administrator {
            get {
                return ResourceManager.GetString("everything_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以其他用户身份运行 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_user {
            get {
                return ResourceManager.GetString("everything_run_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 Everything 搜索 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string everything_search_format {
            get {
                return ResourceManager.GetString("everything_search_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 始终文件夹排在前面 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_always {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序排序时文件夹排在前面 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_ascending {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序排序时文件夹排在前面 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_descending {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹优先显示模式 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_enabled {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]配置文件夹与文件的前后排布规则，可选：升序前置、始终靠前、始终靠后、降序前置 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_enabled_description {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹排在最后 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_never {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        internal static string everything_subtitle_header {
            get {
                return ResourceManager.GetString("everything_subtitle_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview {
            get {
                return ResourceManager.GetString("everything_text_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前文件不支持预览！ 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview_not_supported {
            get {
                return ResourceManager.GetString("everything_text_preview_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  版本 {0} 的本地化字符串。
        /// </summary>
        internal static string everything_version {
            get {
                return ResourceManager.GetString("everything_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 Everything 搜索 的本地化字符串。
        /// </summary>
        internal static string everything_welcome {
            get {
                return ResourceManager.GetString("everything_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键入 ‘Enter’ 键，以获取帮助信息 的本地化字符串。
        /// </summary>
        internal static string everything_welcome_subtitle {
            get {
                return ResourceManager.GetString("everything_welcome_subtitle", resourceCulture);
            }
        }
    }
}
