//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 🔴 Failed to set to clipboard 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_failed {
            get {
                return ResourceManager.GetString("everything_clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🟢 Successfully set to clipboard! 的本地化字符串。
        /// </summary>
        internal static string everything_clipboard_success {
            get {
                return ResourceManager.GetString("everything_clipboard_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string everything_copied {
            get {
                return ResourceManager.GetString("everything_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy file or folder 的本地化字符串。
        /// </summary>
        internal static string everything_copy_file {
            get {
                return ResourceManager.GetString("everything_copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path 的本地化字符串。
        /// </summary>
        internal static string everything_copy_path {
            get {
                return ResourceManager.GetString("everything_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete file 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file {
            get {
                return ResourceManager.GetString("everything_delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete &quot;{0}&quot; file? 的本地化字符串。
        /// </summary>
        internal static string everything_delete_file_tips {
            get {
                return ResourceManager.GetString("everything_delete_file_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete folder 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder {
            get {
                return ResourceManager.GetString("everything_delete_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the &quot;{0}&quot; folder (including its files and subfolders) 的本地化字符串。
        /// </summary>
        internal static string everything_delete_folder_tips {
            get {
                return ResourceManager.GetString("everything_delete_folder_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string everything_delete_tips_caption {
            get {
                return ResourceManager.GetString("everything_delete_tips_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The search matches multiple items 的本地化字符串。
        /// </summary>
        internal static string everything_fallback_multipleResults_subtitle {
            get {
                return ResourceManager.GetString("everything_fallback_multipleResults_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string everything_file_does_not_exit {
            get {
                return ResourceManager.GetString("everything_file_does_not_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a file, not a folder 的本地化字符串。
        /// </summary>
        internal static string everything_file_is_file_not_folder {
            get {
                return ResourceManager.GetString("everything_file_is_file_not_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find files or folders 的本地化字符串。
        /// </summary>
        internal static string everything_find_fallback_display_title {
            get {
                return ResourceManager.GetString("everything_find_fallback_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string everything_folder_browse {
            get {
                return ResourceManager.GetString("everything_folder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This folder is empty 的本地化字符串。
        /// </summary>
        internal static string everything_folder_is_empty {
            get {
                return ResourceManager.GetString("everything_folder_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to open folder at 的本地化字符串。
        /// </summary>
        internal static string everything_folder_open_failed {
            get {
                return ResourceManager.GetString("everything_folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GoBack 的本地化字符串。
        /// </summary>
        internal static string everything_go_back {
            get {
                return ResourceManager.GetString("everything_go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # CmdPal Everything Help Document
        ///&gt; CmdPal Everything is a command panel extension for Windows that allows you to quickly access files and folders in the Everything database through the command panel.
        ///
        ///## Everything Features (Please refer to the official website for details)
        ///- **Quick Access**: Through the command panel, you can quickly find and open files and folders without using the file explorer.
        ///- **Search**: Supports searching for file and folder names, paths, extensions, etc.
        ///- **Sort**: Suppor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string everything_help_content {
            get {
                return ResourceManager.GetString("everything_help_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help document 的本地化字符串。
        /// </summary>
        internal static string everything_help_title {
            get {
                return ResourceManager.GetString("everything_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Ignore Punctuation Marks 的本地化字符串。
        /// </summary>
        internal static string everything_ignorePunctuation_enabled {
            get {
                return ResourceManager.GetString("everything_ignorePunctuation_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically skip all punctuation symbols during keyword parsing and matching. 的本地化字符串。
        /// </summary>
        internal static string everything_ignorePunctuation_enabled_description {
            get {
                return ResourceManager.GetString("everything_ignorePunctuation_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Ignore Whitespace Characters 的本地化字符串。
        /// </summary>
        internal static string everything_ignoreWhitespace_enabled {
            get {
                return ResourceManager.GetString("everything_ignoreWhitespace_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore spaces, tabs and all other whitespace characters in search terms. 的本地化字符串。
        /// </summary>
        internal static string everything_ignoreWhitespace_enabled_description {
            get {
                return ResourceManager.GetString("everything_ignoreWhitespace_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything is not running 的本地化字符串。
        /// </summary>
        internal static string everything_is_not_running {
            get {
                return ResourceManager.GetString("everything_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        internal static string everything_item_tags_name {
            get {
                return ResourceManager.GetString("everything_item_tags_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable macro query 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled {
            get {
                return ResourceManager.GetString("everything_macro_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available doc:,audio:,zip:,pic:,video:,web: and exe: and so filters macro search files 的本地化字符串。
        /// </summary>
        internal static string everything_macro_enabled_description {
            get {
                return ResourceManager.GetString("everything_macro_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case Sensitive Matching 的本地化字符串。
        /// </summary>
        internal static string everything_matchCase_enabled {
            get {
                return ResourceManager.GetString("everything_matchCase_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable case-sensitive search; uppercase and lowercase letters are treated as distinct characters. 的本地化字符串。
        /// </summary>
        internal static string everything_matchCase_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchCase_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Match Diacritics 的本地化字符串。
        /// </summary>
        internal static string everything_matchDiacritics_enabled {
            get {
                return ResourceManager.GetString("everything_matchDiacritics_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distinguish diacritical characters; accented letters won&apos;t match non-accented counterparts. 的本地化字符串。
        /// </summary>
        internal static string everything_matchDiacritics_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchDiacritics_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Path In Search 的本地化字符串。
        /// </summary>
        internal static string everything_matchPath_enabled {
            get {
                return ResourceManager.GetString("everything_matchPath_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search covers full directory paths; keywords match content within folder locations besides filenames. 的本地化字符串。
        /// </summary>
        internal static string everything_matchPath_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchPath_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Prefix Only Match 的本地化字符串。
        /// </summary>
        internal static string everything_matchPrefix_enabled {
            get {
                return ResourceManager.GetString("everything_matchPrefix_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match search term only as the starting prefix of file names or paths. 的本地化字符串。
        /// </summary>
        internal static string everything_matchPrefix_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchPrefix_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Suffix Only Match 的本地化字符串。
        /// </summary>
        internal static string everything_matchSuffix_enabled {
            get {
                return ResourceManager.GetString("everything_matchSuffix_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match search term only as the trailing suffix of file names or paths. 的本地化字符串。
        /// </summary>
        internal static string everything_matchSuffix_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchSuffix_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whole Word Matching 的本地化字符串。
        /// </summary>
        internal static string everything_matchWholeWords_enabled {
            get {
                return ResourceManager.GetString("everything_matchWholeWords_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match whole words only, partial substrings inside words will not be matched. 的本地化字符串。
        /// </summary>
        internal static string everything_matchWholeWords_enabled_description {
            get {
                return ResourceManager.GetString("everything_matchWholeWords_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search result limit 的本地化字符串。
        /// </summary>
        internal static string everything_max_search_result_limit {
            get {
                return ResourceManager.GetString("everything_max_search_result_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of search results returned (too many can cause CmdPal to crash) 的本地化字符串。
        /// </summary>
        internal static string everything_max_search_result_limit_description {
            get {
                return ResourceManager.GetString("everything_max_search_result_limit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string everything_name {
            get {
                return ResourceManager.GetString("everything_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string everything_open {
            get {
                return ResourceManager.GetString("everything_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open containing folder 的本地化字符串。
        /// </summary>
        internal static string everything_open_containing_folder {
            get {
                return ResourceManager.GetString("everything_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder 的本地化字符串。
        /// </summary>
        internal static string everything_open_folder {
            get {
                return ResourceManager.GetString("everything_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open path in console 的本地化字符串。
        /// </summary>
        internal static string everything_open_in_console {
            get {
                return ResourceManager.GetString("everything_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string everything_path {
            get {
                return ResourceManager.GetString("everything_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for files or folders using Everything 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_description {
            get {
                return ResourceManager.GetString("everything_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything Search 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_name {
            get {
                return ResourceManager.GetString("everything_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string everything_plugin_settings {
            get {
                return ResourceManager.GetString("everything_plugin_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything query error 的本地化字符串。
        /// </summary>
        internal static string everything_query_error {
            get {
                return ResourceManager.GetString("everything_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check reconnect 的本地化字符串。
        /// </summary>
        internal static string everything_reconnect {
            get {
                return ResourceManager.GetString("everything_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything service not detected. Please start Everything manually and try again. 的本地化字符串。
        /// </summary>
        internal static string everything_reconnect_fail_message {
            get {
                return ResourceManager.GetString("everything_reconnect_fail_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected successfully after detection! 的本地化字符串。
        /// </summary>
        internal static string everything_reconnect_success_message {
            get {
                return ResourceManager.GetString("everything_reconnect_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_administrator {
            get {
                return ResourceManager.GetString("everything_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as different user 的本地化字符串。
        /// </summary>
        internal static string everything_run_as_user {
            get {
                return ResourceManager.GetString("everything_run_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search with Everything &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string everything_search_format {
            get {
                return ResourceManager.GetString("everything_search_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Show Folders First 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_always {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folders First On Ascending Sort 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_ascending {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folders First On Descending Sort 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_descending {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Sort Priority Rule 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_enabled {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [V3]Configure display priority between folders and files: folders first on ascending/descending sort, always first or always last. 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_enabled_description {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_enabled_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never Show Folders First 的本地化字符串。
        /// </summary>
        internal static string everything_searchFoldersFirst_never {
            get {
                return ResourceManager.GetString("everything_searchFoldersFirst_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        internal static string everything_subtitle_header {
            get {
                return ResourceManager.GetString("everything_subtitle_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview {
            get {
                return ResourceManager.GetString("everything_text_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current file does not support preview！ 的本地化字符串。
        /// </summary>
        internal static string everything_text_preview_not_supported {
            get {
                return ResourceManager.GetString("everything_text_preview_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  version {0} 的本地化字符串。
        /// </summary>
        internal static string everything_version {
            get {
                return ResourceManager.GetString("everything_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to use Everything search 的本地化字符串。
        /// </summary>
        internal static string everything_welcome {
            get {
                return ResourceManager.GetString("everything_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type the &apos;Enter&apos; key for help information 的本地化字符串。
        /// </summary>
        internal static string everything_welcome_subtitle {
            get {
                return ResourceManager.GetString("everything_welcome_subtitle", resourceCulture);
            }
        }
    }
}
